## 複習

In [1]:
news = '''
Coronavirus: Why did infections shoot up South Korea?
South Korea has seen by far the highest numbers of coronavirus cases outside of China - within a week confirmed cases jumped from a few dozen to more than 800.

The country had seemed well prepared and so the skyrocketing numbers have many asking how this happened - and whether a similar sudden outbreak could happen elsewhere.

In South Korea, more than half of the Covid-19 cases have been linked to a religious sect and its critics say the group's secretive nature helped the virus go undetected.

Why did the number of cases spike so suddenly?
Authorities have identified the fringe Christian group Shincheonji Church as being at the heart of this outbreak.

At their services in the south-eastern city of Daegu, members likely infected one another and then fanned out around the country, apparently undetected.

South Korean health officials believe that a 61-year-old member of the sect who last week tested positive for the virus was among the first to be infected and is now at the centre of their investigation.

The female patient initially refused to be transferred to a hospital to be tested and is known to have attended several church gatherings before testing positive.

Any large gathering in a confined space she would have attended - like a church service - would have likely led to further infections, health officials say.

What is coronavirus and what are the symptoms?

The director of the South Korean Centre for Disease Control, Jung Eun-kyeong, suggested at a press briefing that "there is a possibility that the characteristics of many people sitting close together in a very confined space and holding service for more than an hour" would have led to "a few who were exposed infecting many other infectees".

"The virus preys on our social habits and interactions," infectious disease specialist Dr Leong Hoe Nam told the BBC.

"There may be practices within a church - like weeping or the belting of songs - that would encourage droplet transmission."

Another cluster associated with the sect is at a hospital in Cheongdo where a large number of sect followers attended a funeral of the founder's brother over three days at the end of January.

South Korea sees sharp rise in infections

Source: Korea Centers for Disease Control and Prevention (KCDC)
Church communities in other countries have also become virus outbreak clusters, though in much smaller numbers than in South Korea. All of them have suspended services and community gatherings to curb the spread.

So why was it not detected earlier?
Since the outbreak began in China in December, one of the key questions has been how early the virus can be detected - and whether it can be spread by people who don't yet show any symptoms, which would make it very hard to curb the spread.

While Chinese health authorities have long warned people can be contagious before they show any symptoms, the World Health Organization has so far not confirmed that.

South Korea was already on alert over the virus before the clusters were discovered. So if people presumably were careful and paid heightened attention to each others' health, does this then suggest that people without symptoms were able to spread the virus?

"It's a contentious question," says Dale Fisher, chair of the Global Outbreak Alert and Response Network at the WHO, told the BBC.

"What we can say is that it spreads early - whereas Sars (severe acute respiratory syndrome) for instance spread late in the illness."

He explains that any infected people will have the virus on their throat before they show any symptoms. Yet without the symptoms - without coughing - they are also much less likely to spread the virus.

Simply put, in order to spread the virus widely, an infected person would need to be coughing, i.e. coughing on their hands, on surfaces or on other people.

"At worst, the infectivity in an infected person without symptoms is much lower," Mr Fisher explains. "And to be clear - the asymptomatic ones are not the big spreaders. It is only when you do have symptoms that you can spread it easily."

Coronavirus: A visual guide to the outbreak
How a misleading coronavirus map went global
Watching loved ones die without care in Wuhan
What do we know about Shincheonji?
Officially called the Shincheonji Church of Jesus the Temple of the Tabernacle of the Testimony, the group was founded in the 1980s and claims to have around 250,000 followers.

During services, the members are reportedly asked to sit and kneel very close to one another and continue to gather after the service is over.

The fringe Christian mega church is accused by some critics of being a cult.


It is common to hide your membership of Shincheonji Church as they are not a popular sect in South Korea, says the BBC's South Korea correspondent Laura Bicker.

They also see sickness as a weakness. This combination means tracking those who've been infected has proven difficult. There are still some church-goers the health authorities have not managed to trace, despite the religious sect calling on its members to co-operate.

The group itself though says it is fully cooperating with authorities, and that it has closed down its more than 1,000 churches and asked members to refrain from any outside activities.

Yet there is a lot of anger and blame being directed at the sect.

Hundreds of thousands have called for the dissolution of the Shincheonji Church of Jesus. Over 552,000 people have signed an online petition since Saturday after it was filed on the website of the presidential office of Cheong Wa-dae.

"Shincheonji contributed significantly to the sharp rise in the number of patients in Korea," Won Suk-choi of the division of infectious diseases at the Korea University College of Medicine, told the BBC, but he also warns that "the situation Korea is currently experiencing can happen anywhere in the world".

How are South Koreans reacting?
There is fear in South Korea, especially for elderly parents and relatives, according to our correspondent, who is in the worst-hit city of Daegu.

Yet there is also resigned acceptance and many South Koreans believe the country was well prepared for this outbreak.

Medics and hospitals have been on standby for weeks. There are briefings from the Centre for Disease Control twice a day where experts have been mapping the source of every infection.
There are also text messages alerting residents to confirmed cases in their area telling you where they've been and when.

Unlike Hong Kong or Singapore, there had been very little panic buying in South Korea until the beginning of the week.

Yet when shops in Daegu announced they had new stock of masks arriving, thousands queued for hours in the hope of getting one.

'''

In [17]:
stopwords = ["a", "about", "above", "above", "across", "after", "afterwards", "again", "against", "all", "almost", "alone", "along", "already", "also","although","always","am","among", "amongst", "amoungst", "amount",  "an", "and", "another", "any","anyhow","anyone","anything","anyway", "anywhere", "are", "around", "as",  "at", "back","be","became", "because","become","becomes", "becoming", "been", "before", "beforehand", "behind", "being", "below", "beside", "besides", "between", "beyond", "bill", "both", "bottom","but", "by", "call", "can", "cannot", "cant", "co", "con", "could", "couldnt", "cry", "de", "describe", "detail", "do", "done", "down", "due", "during", "each", "eg", "eight", "either", "eleven","else", "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone", "everything", "everywhere", "except", "few", "fifteen", "fify", "fill", "find", "fire", "first", "five", "for", "former", "formerly", "forty", "found", "four", "from", "front", "full", "further", "get", "give", "go", "had", "has", "hasnt", "have", "he", "hence", "her", "here", "hereafter", "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his", "how", "however", "hundred", "ie", "if", "in", "inc", "indeed", "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter", "latterly", "least", "less", "ltd", "made", "many", "may", "me", "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly", "move", "much", "must", "my", "myself", "name", "namely", "neither", "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone", "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on", "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our", "ours", "ourselves", "out", "over", "own","part", "per", "perhaps", "please", "put", "rather", "re", "same", "see", "seem", "seemed", "seeming", "seems", "serious", "several", "she", "should", "show", "side", "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone", "something", "sometime", "sometimes", "somewhere", "still", "such", "system", "take", "ten", "than", "that", "the", "their", "them", "themselves", "then", "thence", "there", "thereafter", "thereby", "therefore", "therein", "thereupon", "these", "they", "thick", "thin", "third", "this", "those", "though", "three", "through", "throughout", "thru", "thus", "to", "together", "too", "top", "toward", "towards", "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us", "very", "via", "was", "we", "well", "were", "what", "whatever", "when", "whence", "whenever", "where", "whereafter", "whereas", "whereby", "wherein", "whereupon", "wherever", "whether", "which", "while", "whither", "who", "whoever", "whole", "whom", "whose", "why", "will", "with", "within", "without", "would", "yet", "you", "your", "yours", "yourself", "yourselves", "the"]

In [18]:
words = news.lower().split()

In [19]:
type(words)

list

In [20]:
dic = {}
for w in words:
    if w not in stopwords:
        if w not in dic:
            dic[w] = 1
        else:
            dic[w] = dic[w] + 1

In [21]:
?sorted

In [22]:
a = ('why', 3)
def getSecond(e):
    return e[1]

getSecond(a)

getSecond2 = lambda e : e[1]
getSecond2(a)

3

In [23]:
swd = sorted(dic.items(), key = lambda e : e[1], reverse=True )

In [25]:
swd[0:20]

[('south', 14),
 ('-', 11),
 ('church', 9),
 ('korea', 8),
 ('virus', 8),
 ('people', 7),
 ('sect', 6),
 ('infected', 6),
 ('spread', 6),
 ('cases', 5),
 ('outbreak', 5),
 ('health', 5),
 ('shincheonji', 4),
 ('members', 4),
 ('disease', 4),
 ('symptoms', 4),
 ('numbers', 3),
 ('coronavirus', 3),
 ('confirmed', 3),
 ('korea,', 3)]

## 套件與模組

In [26]:
a = [10,20,30]
sum(a)

60

In [27]:
sum = 50

In [28]:
sum(a)

TypeError: 'int' object is not callable

In [29]:
import test

In [30]:
test.var

1

In [31]:
test.f('hello')

'hello'

In [33]:
def f(a):
    return a + 3
f(5)

8

In [35]:
from test import f
f(5)

5

In [36]:
from test import f as h
print(h('David'))


David


In [37]:
from test import * 
print(var)

1


In [38]:
f('hello')

'hello'

In [39]:
from child import test

In [40]:
test.var

1

In [41]:
test.f('Hello')

'Hello'

## 第三方套件

In [52]:
! pip install PyAudio

You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [42]:
! pip install SpeechRecognition

You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [44]:
import speech_recognition as sr

r = sr.Recognizer()
with sr.Microphone() as source:
    audio = r.listen(source)
    print(r.recognize_google(audio, language='zh_TW'))

大家好


In [46]:
def listenTo():
    r = sr.Recognizer()
    with sr.Microphone() as source:
        audio = r.listen(source)
        return r.recognize_google(audio, language='zh_TW')

In [50]:
qa = {
    '我要保險': '以下是目前我們提供的保險服務',
    '我要貸款': '以下是目前我們提供的貸款服務',
    '我還有多少錢': '你的餘額剩下'
}

qa.get(listenTo(), '我現在還不聰明，等我變聰明以後再告訴你')

'我現在還不聰明，等我變聰明以後再告訴你'

In [51]:
! pip install gTTS

You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [53]:
! pip install pygame

You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [55]:
from gtts import gTTS
tts = gTTS('hello i love taipei fubon')
tts.save('hello.mp3')

In [57]:
from gtts import gTTS
tts = gTTS('麻雀雖小 五臟俱全 中國雖大 武漢肺炎', lang='zh-TW')
tts.save('hello.mp3')

In [58]:
from gtts import gTTS
from pygame import mixer
mixer.init()

import tempfile
def speak(sentence):
    with tempfile.NamedTemporaryFile(delete=True) as fp:
        tts = gTTS(text=sentence, lang='zh-tw')
        tts.save("{}.mp3".format(fp.name))
        mixer.music.load('{}.mp3'.format(fp.name))
        mixer.music.play()


In [59]:
speak('麻雀雖小 五臟俱全 中國雖大 武漢肺炎')

In [62]:
qa = {
    '我要保險': '以下是目前我們提供的保險服務',
    '我要貸款': '以下是目前我們提供的貸款服務',
    '我還有多少錢': '你的餘額剩下'
}

speak(qa.get(listenTo(), '我現在還不聰明，等我變聰明以後再告訴你'))

## Numpy

In [72]:
a = [1,3,5,7,9]
b = [2,4,6,8,10]

In [73]:
ary = []
for i in range(0, len(a)):
    ary.append(a[i] * b[i])
ary

[2, 12, 30, 56, 90]

In [74]:
for e in zip(a,b):
    print(e)

(1, 2)
(3, 4)
(5, 6)
(7, 8)
(9, 10)


In [75]:
i,j = (1, 2)

In [76]:
for i,j in zip(a,b):
    print(i,j)

1 2
3 4
5 6
7 8
9 10


In [77]:
ary = []
for i,j in zip(a,b):
    ary.append(i*j)
ary

[2, 12, 30, 56, 90]

In [78]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [79]:
import numpy
na = numpy.array(a)
nb = numpy.array(b)


In [81]:
a

[1, 3, 5, 7, 9]

In [82]:
type(a)

list

In [80]:
na

array([1, 3, 5, 7, 9])

In [83]:
type(na)

numpy.ndarray

In [84]:
na * nb

array([ 2, 12, 30, 56, 90])

In [85]:
import numpy as np
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [86]:
my_matrix = [ [1,2,3], [4,5,6], [7,8,9] ]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [91]:
np.zeros(3)
np.zeros((5,5))
np.ones(3)
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [92]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [95]:
#np.linspace(0,10,50)

In [96]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [97]:
#產生隨機數列
np.random.rand(2)
np.random.rand(5,5)

np.random.randn(2)
np.random.randn(5,5)

np.random.randint(1,100)
np.random.randint(1,100,10)


array([21, 50, 87, 80, 74, 31, 95, 99,  5,  3])

In [99]:
arr = np.arange(25)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [100]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [101]:
ranarr = np.random.randint(0,50,10)
ranarr

array([32, 48, 30,  7, 17, 24,  9,  0, 48,  0])

In [102]:
ranarr.max()

48

In [103]:
ranarr.min()

0

In [104]:
ranarr.argmax()

1

In [105]:
ranarr.argmin()

7

In [106]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [107]:
arr.shape

(25,)

In [108]:
arr.reshape((1,25))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [109]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [110]:
arr.dtype

dtype('int64')

In [111]:
arr = np.arange(0,11)

In [112]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
arr[8]

8

In [115]:
arr[1:5]

array([1, 2, 3, 4])

In [116]:
arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [118]:
slice_of_arr[:]=99

In [119]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [120]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [121]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [122]:
arr_2d[1]


array([20, 25, 30])

In [123]:
arr_2d[1][0]


20

In [124]:
arr_2d[1,0]


20

In [125]:
arr_2d[2]


array([35, 40, 45])

In [126]:
arr_2d[2,:]

array([35, 40, 45])

In [127]:
arr_2d[2,1:]

array([40, 45])

In [128]:
arr = np.arange(1,11)


In [129]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [130]:
arr > 4


array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [131]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [132]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [134]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [135]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [136]:
arr / arr

/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [137]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [138]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## Pandas

In [140]:
import numpy as np

In [141]:
na = np.array([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
na               

array([['frank', 'M', '29'],
       ['mary', 'F', '23'],
       ['tom', 'M', '35'],
       ['ted', 'M', '33'],
       ['jean', 'F', '21'],
       ['lisa', 'F', '20']], dtype='<U5')

In [142]:
import numpy as np
na = np.array([['name', 'gender', 'age'], ['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
na 


array([['name', 'gender', 'age'],
       ['frank', 'M', '29'],
       ['mary', 'F', '23'],
       ['tom', 'M', '35'],
       ['ted', 'M', '33'],
       ['jean', 'F', '21'],
       ['lisa', 'F', '20']], dtype='<U6')

In [148]:
# select avg(age) from na;
na[:,2][1:].astype(int).mean()

26.833333333333332

In [149]:
import pandas as pd
df = pd.DataFrame([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
df

0  1   2
0  frank  M  29
1   mary  F  23
2    tom  M  35
3    ted  M  33
4   jean  F  21
5   lisa  F  20

In [150]:
df.columns=['name', 'gender', 'age']
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [152]:
df['age'].mean()

26.833333333333332

## Pandas Series

In [153]:
# 從List 建立Series
labels = ['a','b','c']
my_list = [10,20,30]

type(labels)

list

In [154]:
type(my_list)

list

In [155]:
# 建立Series
import numpy as np
import pandas as pd

# 從List 建立Series
labels = ['a','b','c']
my_list = [10,20,30]

pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [158]:
a = pd.Series(data=my_list,index=labels)
a

a    10
b    20
c    30
dtype: int64

In [159]:
a['b']

20

In [160]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [161]:
arr = np.array([10,20,30])
arr


array([10, 20, 30])

In [162]:
type(arr)

numpy.ndarray

In [163]:
pd.Series(arr)


0    10
1    20
2    30
dtype: int64

In [164]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [165]:
d = {'a':10,'b':20,'c':30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

## Pandas DataFrame

In [166]:
df = pd.DataFrame([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
df.columns = ['name', 'gender', 'age']
df


name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [167]:
df = pd.DataFrame([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]], columns = ['name', 'gender', 'age'])
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [169]:
df2 = pd.DataFrame([{'name':'frank', 'gender':'M', 'age':29}, \
                   {'name':'mary',  'gender':'F', 'age':23}, \
                   {'name':'tom',   'gender':'M', 'age':35}, \
                   {'name':'ted',   'gender':'M', 'age':33}, \
                   {'name':'jean',  'gender':'F'}, \
                   {'name':'lisa',  'gender':'F', 'age':20}])
df2

age gender   name
0  29.0      M  frank
1  23.0      F   mary
2  35.0      M    tom
3  33.0      M    ted
4   NaN      F   jean
5  20.0      F   lisa

In [168]:
df = pd.DataFrame([{'name':'frank', 'gender':'M', 'age':29}, \
                   {'name':'mary',  'gender':'F', 'age':23}, \
                   {'name':'tom',   'gender':'M', 'age':35}, \
                   {'name':'ted',   'gender':'M', 'age':33}, \
                   {'name':'jean',  'gender':'F', 'age':21}, \
                   {'name':'lisa',  'gender':'F', 'age':20}])
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [170]:
df.head(3)

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom

In [171]:
df.tail(3)

age gender  name
3   33      M   ted
4   21      F  jean
5   20      F  lisa

In [172]:
df.head()

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
age       6 non-null int64
gender    6 non-null object
name      6 non-null object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


In [174]:
df.describe()

age
count   6.000000
mean   26.833333
std     6.400521
min    20.000000
25%    21.500000
50%    26.000000
75%    32.000000
max    35.000000

In [175]:
df.dtypes

age        int64
gender    object
name      object
dtype: object

In [177]:
# select name from df;
df['name']

0    frank
1     mary
2      tom
3      ted
4     jean
5     lisa
Name: name, dtype: object

In [178]:
# select name, age from df;
df[['name', 'age']]

name  age
0  frank   29
1   mary   23
2    tom   35
3    ted   33
4   jean   21
5   lisa   20

In [179]:
# select * from df where gender = M
df['gender']

0    M
1    F
2    M
3    M
4    F
5    F
Name: gender, dtype: object

In [180]:
df['gender'] == 'M'

0     True
1    False
2     True
3     True
4    False
5    False
Name: gender, dtype: bool

In [181]:
df[df['gender'] == 'M']

age gender   name
0   29      M  frank
2   35      M    tom
3   33      M    ted

In [182]:
(df['gender'] == 'M') & (df['age'] >= 30)

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [183]:
df[(df['gender'] == 'M') & (df['age'] >= 30)]

age gender name
2   35      M  tom
3   33      M  ted

In [184]:
df[(df['gender'] == 'M') | (df['age'] >= 30) ]

age gender   name
0   29      M  frank
2   35      M    tom
3   33      M    ted

In [186]:
df['employee'] = True

In [187]:
df

age gender   name  employee
0   29      M  frank      True
1   23      F   mary      True
2   35      M    tom      True
3   33      M    ted      True
4   21      F   jean      True
5   20      F   lisa      True

In [189]:
a = 3
a

3

In [190]:
del a

In [191]:
a

NameError: name 'a' is not defined

In [192]:
del df['employee']

In [193]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [194]:
df['employee'] = True

In [195]:
df

age gender   name  employee
0   29      M  frank      True
1   23      F   mary      True
2   35      M    tom      True
3   33      M    ted      True
4   21      F   jean      True
5   20      F   lisa      True

In [198]:
# 如果沒有加inplace=True, 不會立即生效
df.drop('employee', axis = 1)

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [199]:
df

age gender   name  employee
0   29      M  frank      True
1   23      F   mary      True
2   35      M    tom      True
3   33      M    ted      True
4   21      F   jean      True
5   20      F   lisa      True

In [200]:
df.drop('employee', axis = 1, inplace=True)

In [201]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [203]:
df['userid'] = range(101,107)

In [204]:
df

age gender   name  userid
0   29      M  frank     101
1   23      F   mary     102
2   35      M    tom     103
3   33      M    ted     104
4   21      F   jean     105
5   20      F   lisa     106

In [205]:
df.set_index('userid', inplace=True)

In [206]:
df

age gender   name
userid                   
101      29      M  frank
102      23      F   mary
103      35      M    tom
104      33      M    ted
105      21      F   jean
106      20      F   lisa

In [208]:
df.iloc[1]

age         23
gender       F
name      mary
Name: 102, dtype: object

In [209]:
df.iloc[[1,3,5]]

age gender  name
userid                  
102      23      F  mary
104      33      M   ted
106      20      F  lisa

In [210]:
df.loc[102]

age         23
gender       F
name      mary
Name: 102, dtype: object

In [211]:
df.loc[[102,104,106]]

age gender  name
userid                  
102      23      F  mary
104      33      M   ted
106      20      F  lisa

In [212]:
df.loc[[102,104,106], ['gender','name'] ]


gender  name
userid             
102         F  mary
104         M   ted
106         F  lisa

In [213]:
df

age gender   name
userid                   
101      29      M  frank
102      23      F   mary
103      35      M    tom
104      33      M    ted
105      21      F   jean
106      20      F   lisa

In [218]:
df[df['gender'] == 'M']['age'].mean()

32.333333333333336

In [219]:
df[df['gender'] == 'F']['age'].mean()

21.333333333333332

In [221]:
# select gender, avg(age) from df group by gender
df.groupby('gender')['age'].mean()

gender
F    21.333333
M    32.333333
Name: age, dtype: float64

In [222]:
import pandas as pd
names1880 = pd.read_csv('https://raw.githubusercontent.com/ywchiu/taipeifubon/master/data/yob1880.txt', names = ['name', 'sex', 'births'])

In [224]:
names1880.head()

name sex  births
0       Mary   F    7065
1       Anna   F    2604
2       Emma   F    2003
3  Elizabeth   F    1939
4     Minnie   F    1746

In [225]:
names1880.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 3 columns):
name      2000 non-null object
sex       2000 non-null object
births    2000 non-null int64
dtypes: int64(1), object(2)
memory usage: 47.0+ KB


In [226]:
names1880.describe()

births
count  2000.000000
mean    100.743000
std     466.120297
min       5.000000
25%       7.000000
50%      13.000000
75%      41.250000
max    9655.000000

In [228]:
names1880['sex'].unique()

array(['F', 'M'], dtype=object)

In [231]:
# SELECT sex, SUM(births) FROM names1880 GROUP BY sex
names1880.groupby('sex')['births'].sum()

sex
F     90993
M    110493
Name: births, dtype: int64