In [2]:
a = [1,2,3]
b = [2,3,4]
for i,j in zip(a,b):
    print(i * j)

2
6
12


In [3]:
import numpy
na = numpy.array(a)
nb = numpy.array(b)

In [4]:
na * nb

array([ 2,  6, 12])

In [8]:
import numpy as np

def threshold_function(x):
    y = x > 0
    #return y
    return y.astype(int)

x = np.array([-1,1,2])
threshold_function(x)

array([0, 1, 1])

In [9]:
def sigmoid_function(x):
    return 1/ (1 + np.exp(-x))
sigmoid_function(x)

array([0.26894142, 0.73105858, 0.88079708])

In [10]:
def tangent_function(x):
    return (1 - np.exp(-2*x)) / (1 + np.exp(-2*x))


In [11]:
x = np.array([-1,1,2])
tangent_function(x)


array([-0.76159416,  0.76159416,  0.96402758])

In [12]:
np.tanh(x)



array([-0.76159416,  0.76159416,  0.96402758])

In [13]:
def relu_function(x):
    return np.maximum(0,x)

x = np.array([-1,1,2])
relu_function(x)


array([0, 1, 2])

In [14]:
import numpy as np
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])
#Y = np.dot(X,W)
#Y
X.shape, W.shape

((2,), (2, 3))

In [15]:
np.dot(X,W)

array([ 5, 11, 17])

In [16]:
network = {}
network['w1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
network['b1'] = np.array([0.1,0.2,0.3])
network['w2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
network['b2'] = np.array([0.1,0.2])


In [17]:
network['w1'].shape

(2, 3)

In [18]:
network['b1'].shape

(3,)

In [19]:
network['w2'].shape

(3, 2)

In [20]:
network['b2'].shape

(2,)

In [21]:
2 * 3 + 3 + 3 * 2 + 2

17

In [22]:
x = np.array([1,0.5])

In [25]:
a = np.dot(x, network['w1']) + network['b1']

In [26]:
a

array([0.3, 0.7, 1.1])

In [28]:
z = sigmoid_function(a)
z

array([0.57444252, 0.66818777, 0.75026011])

In [29]:
y = np.dot(z, network['w2']) + network['b2']
y

array([0.51615984, 1.21402696])

In [30]:
def softmax_function(x):
    return np.exp(x) / np.sum(np.exp(x))

softmax_function(y)


array([0.33228528, 0.66771472])

## 小任務
- 如果有一個兩層神經網路，輸入層有四個神經元，隱藏層有五個神經元，輸出層有三個神經元，試問：整個網路有多少參數?